# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class AnalyticsSubsetAnyOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NUM_OF_UE_REG = "NUM_OF_UE_REG"
    NUM_OF_PDU_SESS_ESTBL = "NUM_OF_PDU_SESS_ESTBL"
    RES_USAGE = "RES_USAGE"
    NUM_OF_EXCEED_RES_USAGE_LOAD_LEVEL_THR = "NUM_OF_EXCEED_RES_USAGE_LOAD_LEVEL_THR"
    PERIOD_OF_EXCEED_RES_USAGE_LOAD_LEVEL_THR = "PERIOD_OF_EXCEED_RES_USAGE_LOAD_LEVEL_THR"
    EXCEED_LOAD_LEVEL_THR_IND = "EXCEED_LOAD_LEVEL_THR_IND"
    LIST_OF_TOP_APP_UL = "LIST_OF_TOP_APP_UL"
    LIST_OF_TOP_APP_DL = "LIST_OF_TOP_APP_DL"
    def __init__(self):  # noqa: E501
        """AnalyticsSubsetAnyOf - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'AnalyticsSubsetAnyOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AnalyticsSubset_anyOf of this AnalyticsSubsetAnyOf.  # noqa: E501
        :rtype: AnalyticsSubsetAnyOf
        """
        return util.deserialize_model(dikt, cls)
