# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.network_area_info import NetworkAreaInfo
from openapi_server.models.rat_type import RatType
from openapi_server.models.snssai import Snssai
from openapi_server.models.svc_experience import SvcExperience
from openapi_server import util

from openapi_server.models.network_area_info import NetworkAreaInfo  # noqa: E501
from openapi_server.models.rat_type import RatType  # noqa: E501
from openapi_server.models.snssai import Snssai  # noqa: E501
from openapi_server.models.svc_experience import SvcExperience  # noqa: E501

class ServiceExperienceInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, svc_exprc=None, svc_exprc_variance=None, supis=None, snssai=None, app_id=None, confidence=None, dnn=None, network_area=None, nsi_id=None, ratio=None, rat_type=None, frequency=None):  # noqa: E501
        """ServiceExperienceInfo - a model defined in OpenAPI

        :param svc_exprc: The svc_exprc of this ServiceExperienceInfo.  # noqa: E501
        :type svc_exprc: SvcExperience
        :param svc_exprc_variance: The svc_exprc_variance of this ServiceExperienceInfo.  # noqa: E501
        :type svc_exprc_variance: float
        :param supis: The supis of this ServiceExperienceInfo.  # noqa: E501
        :type supis: List[str]
        :param snssai: The snssai of this ServiceExperienceInfo.  # noqa: E501
        :type snssai: Snssai
        :param app_id: The app_id of this ServiceExperienceInfo.  # noqa: E501
        :type app_id: str
        :param confidence: The confidence of this ServiceExperienceInfo.  # noqa: E501
        :type confidence: int
        :param dnn: The dnn of this ServiceExperienceInfo.  # noqa: E501
        :type dnn: str
        :param network_area: The network_area of this ServiceExperienceInfo.  # noqa: E501
        :type network_area: NetworkAreaInfo
        :param nsi_id: The nsi_id of this ServiceExperienceInfo.  # noqa: E501
        :type nsi_id: str
        :param ratio: The ratio of this ServiceExperienceInfo.  # noqa: E501
        :type ratio: int
        :param rat_type: The rat_type of this ServiceExperienceInfo.  # noqa: E501
        :type rat_type: RatType
        :param frequency: The frequency of this ServiceExperienceInfo.  # noqa: E501
        :type frequency: int
        """
        self.openapi_types = {
            'svc_exprc': SvcExperience,
            'svc_exprc_variance': float,
            'supis': List[str],
            'snssai': Snssai,
            'app_id': str,
            'confidence': int,
            'dnn': str,
            'network_area': NetworkAreaInfo,
            'nsi_id': str,
            'ratio': int,
            'rat_type': RatType,
            'frequency': int
        }

        self.attribute_map = {
            'svc_exprc': 'svcExprc',
            'svc_exprc_variance': 'svcExprcVariance',
            'supis': 'supis',
            'snssai': 'snssai',
            'app_id': 'appId',
            'confidence': 'confidence',
            'dnn': 'dnn',
            'network_area': 'networkArea',
            'nsi_id': 'nsiId',
            'ratio': 'ratio',
            'rat_type': 'ratType',
            'frequency': 'frequency'
        }

        self._svc_exprc = svc_exprc
        self._svc_exprc_variance = svc_exprc_variance
        self._supis = supis
        self._snssai = snssai
        self._app_id = app_id
        self._confidence = confidence
        self._dnn = dnn
        self._network_area = network_area
        self._nsi_id = nsi_id
        self._ratio = ratio
        self._rat_type = rat_type
        self._frequency = frequency

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceExperienceInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceExperienceInfo of this ServiceExperienceInfo.  # noqa: E501
        :rtype: ServiceExperienceInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def svc_exprc(self):
        """Gets the svc_exprc of this ServiceExperienceInfo.


        :return: The svc_exprc of this ServiceExperienceInfo.
        :rtype: SvcExperience
        """
        return self._svc_exprc

    @svc_exprc.setter
    def svc_exprc(self, svc_exprc):
        """Sets the svc_exprc of this ServiceExperienceInfo.


        :param svc_exprc: The svc_exprc of this ServiceExperienceInfo.
        :type svc_exprc: SvcExperience
        """
        if svc_exprc is None:
            raise ValueError("Invalid value for `svc_exprc`, must not be `None`")  # noqa: E501

        self._svc_exprc = svc_exprc

    @property
    def svc_exprc_variance(self):
        """Gets the svc_exprc_variance of this ServiceExperienceInfo.

        string with format \"float\" as defined in OpenAPI.  # noqa: E501

        :return: The svc_exprc_variance of this ServiceExperienceInfo.
        :rtype: float
        """
        return self._svc_exprc_variance

    @svc_exprc_variance.setter
    def svc_exprc_variance(self, svc_exprc_variance):
        """Sets the svc_exprc_variance of this ServiceExperienceInfo.

        string with format \"float\" as defined in OpenAPI.  # noqa: E501

        :param svc_exprc_variance: The svc_exprc_variance of this ServiceExperienceInfo.
        :type svc_exprc_variance: float
        """

        self._svc_exprc_variance = svc_exprc_variance

    @property
    def supis(self):
        """Gets the supis of this ServiceExperienceInfo.


        :return: The supis of this ServiceExperienceInfo.
        :rtype: List[str]
        """
        return self._supis

    @supis.setter
    def supis(self, supis):
        """Sets the supis of this ServiceExperienceInfo.


        :param supis: The supis of this ServiceExperienceInfo.
        :type supis: List[str]
        """
        if supis is not None and len(supis) < 1:
            raise ValueError("Invalid value for `supis`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._supis = supis

    @property
    def snssai(self):
        """Gets the snssai of this ServiceExperienceInfo.


        :return: The snssai of this ServiceExperienceInfo.
        :rtype: Snssai
        """
        return self._snssai

    @snssai.setter
    def snssai(self, snssai):
        """Sets the snssai of this ServiceExperienceInfo.


        :param snssai: The snssai of this ServiceExperienceInfo.
        :type snssai: Snssai
        """

        self._snssai = snssai

    @property
    def app_id(self):
        """Gets the app_id of this ServiceExperienceInfo.

        String providing an application identifier.  # noqa: E501

        :return: The app_id of this ServiceExperienceInfo.
        :rtype: str
        """
        return self._app_id

    @app_id.setter
    def app_id(self, app_id):
        """Sets the app_id of this ServiceExperienceInfo.

        String providing an application identifier.  # noqa: E501

        :param app_id: The app_id of this ServiceExperienceInfo.
        :type app_id: str
        """

        self._app_id = app_id

    @property
    def confidence(self):
        """Gets the confidence of this ServiceExperienceInfo.

        Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.  # noqa: E501

        :return: The confidence of this ServiceExperienceInfo.
        :rtype: int
        """
        return self._confidence

    @confidence.setter
    def confidence(self, confidence):
        """Sets the confidence of this ServiceExperienceInfo.

        Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.  # noqa: E501

        :param confidence: The confidence of this ServiceExperienceInfo.
        :type confidence: int
        """
        if confidence is not None and confidence < 0:  # noqa: E501
            raise ValueError("Invalid value for `confidence`, must be a value greater than or equal to `0`")  # noqa: E501

        self._confidence = confidence

    @property
    def dnn(self):
        """Gets the dnn of this ServiceExperienceInfo.

        String representing a Data Network as defined in clause 9A of 3GPP TS 23.003; it shall contain either a DNN Network Identifier, or a full DNN with both the Network Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots (e.g. \"Label1.Label2.Label3\").  # noqa: E501

        :return: The dnn of this ServiceExperienceInfo.
        :rtype: str
        """
        return self._dnn

    @dnn.setter
    def dnn(self, dnn):
        """Sets the dnn of this ServiceExperienceInfo.

        String representing a Data Network as defined in clause 9A of 3GPP TS 23.003; it shall contain either a DNN Network Identifier, or a full DNN with both the Network Identifier and Operator Identifier, as specified in 3GPP TS 23.003 clause 9.1.1 and 9.1.2. It shall be coded as string in which the labels are separated by dots (e.g. \"Label1.Label2.Label3\").  # noqa: E501

        :param dnn: The dnn of this ServiceExperienceInfo.
        :type dnn: str
        """

        self._dnn = dnn

    @property
    def network_area(self):
        """Gets the network_area of this ServiceExperienceInfo.


        :return: The network_area of this ServiceExperienceInfo.
        :rtype: NetworkAreaInfo
        """
        return self._network_area

    @network_area.setter
    def network_area(self, network_area):
        """Sets the network_area of this ServiceExperienceInfo.


        :param network_area: The network_area of this ServiceExperienceInfo.
        :type network_area: NetworkAreaInfo
        """

        self._network_area = network_area

    @property
    def nsi_id(self):
        """Gets the nsi_id of this ServiceExperienceInfo.

        Contains the Identifier of the selected Network Slice instance  # noqa: E501

        :return: The nsi_id of this ServiceExperienceInfo.
        :rtype: str
        """
        return self._nsi_id

    @nsi_id.setter
    def nsi_id(self, nsi_id):
        """Sets the nsi_id of this ServiceExperienceInfo.

        Contains the Identifier of the selected Network Slice instance  # noqa: E501

        :param nsi_id: The nsi_id of this ServiceExperienceInfo.
        :type nsi_id: str
        """

        self._nsi_id = nsi_id

    @property
    def ratio(self):
        """Gets the ratio of this ServiceExperienceInfo.

        Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.  # noqa: E501

        :return: The ratio of this ServiceExperienceInfo.
        :rtype: int
        """
        return self._ratio

    @ratio.setter
    def ratio(self, ratio):
        """Sets the ratio of this ServiceExperienceInfo.

        Unsigned integer indicating Sampling Ratio (see clauses 4.15.1 of 3GPP TS 23.502), expressed in percent.  # noqa: E501

        :param ratio: The ratio of this ServiceExperienceInfo.
        :type ratio: int
        """
        if ratio is not None and ratio > 100:  # noqa: E501
            raise ValueError("Invalid value for `ratio`, must be a value less than or equal to `100`")  # noqa: E501
        if ratio is not None and ratio < 1:  # noqa: E501
            raise ValueError("Invalid value for `ratio`, must be a value greater than or equal to `1`")  # noqa: E501

        self._ratio = ratio

    @property
    def rat_type(self):
        """Gets the rat_type of this ServiceExperienceInfo.


        :return: The rat_type of this ServiceExperienceInfo.
        :rtype: RatType
        """
        return self._rat_type

    @rat_type.setter
    def rat_type(self, rat_type):
        """Sets the rat_type of this ServiceExperienceInfo.


        :param rat_type: The rat_type of this ServiceExperienceInfo.
        :type rat_type: RatType
        """

        self._rat_type = rat_type

    @property
    def frequency(self):
        """Gets the frequency of this ServiceExperienceInfo.

        Integer value indicating the ARFCN applicable for a downlink, uplink or bi-directional (TDD) NR global frequency raster, as definition of \"ARFCN-ValueNR\" IE in clause 6.3.2 of 3GPP TS 38.331.  # noqa: E501

        :return: The frequency of this ServiceExperienceInfo.
        :rtype: int
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency):
        """Sets the frequency of this ServiceExperienceInfo.

        Integer value indicating the ARFCN applicable for a downlink, uplink or bi-directional (TDD) NR global frequency raster, as definition of \"ARFCN-ValueNR\" IE in clause 6.3.2 of 3GPP TS 38.331.  # noqa: E501

        :param frequency: The frequency of this ServiceExperienceInfo.
        :type frequency: int
        """
        if frequency is not None and frequency > 3279165:  # noqa: E501
            raise ValueError("Invalid value for `frequency`, must be a value less than or equal to `3279165`")  # noqa: E501
        if frequency is not None and frequency < 0:  # noqa: E501
            raise ValueError("Invalid value for `frequency`, must be a value greater than or equal to `0`")  # noqa: E501

        self._frequency = frequency
