# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.number_average import NumberAverage
from openapi_server.models.snssai import Snssai
from openapi_server import util

from openapi_server.models.number_average import NumberAverage  # noqa: E501
from openapi_server.models.snssai import Snssai  # noqa: E501

class SliceLoadLevelInformation(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, load_level_information=None, snssais=None, num_of_ues=None, num_of_pdu_sess=None, exceed_load_level_thr_ind=None, confidence=None):  # noqa: E501
        """SliceLoadLevelInformation - a model defined in OpenAPI

        :param load_level_information: The load_level_information of this SliceLoadLevelInformation.  # noqa: E501
        :type load_level_information: int
        :param snssais: The snssais of this SliceLoadLevelInformation.  # noqa: E501
        :type snssais: List[Snssai]
        :param num_of_ues: The num_of_ues of this SliceLoadLevelInformation.  # noqa: E501
        :type num_of_ues: NumberAverage
        :param num_of_pdu_sess: The num_of_pdu_sess of this SliceLoadLevelInformation.  # noqa: E501
        :type num_of_pdu_sess: NumberAverage
        :param exceed_load_level_thr_ind: The exceed_load_level_thr_ind of this SliceLoadLevelInformation.  # noqa: E501
        :type exceed_load_level_thr_ind: bool
        :param confidence: The confidence of this SliceLoadLevelInformation.  # noqa: E501
        :type confidence: int
        """
        self.openapi_types = {
            'load_level_information': int,
            'snssais': List[Snssai],
            'num_of_ues': NumberAverage,
            'num_of_pdu_sess': NumberAverage,
            'exceed_load_level_thr_ind': bool,
            'confidence': int
        }

        self.attribute_map = {
            'load_level_information': 'loadLevelInformation',
            'snssais': 'snssais',
            'num_of_ues': 'numOfUes',
            'num_of_pdu_sess': 'numOfPduSess',
            'exceed_load_level_thr_ind': 'exceedLoadLevelThrInd',
            'confidence': 'confidence'
        }

        self._load_level_information = load_level_information
        self._snssais = snssais
        self._num_of_ues = num_of_ues
        self._num_of_pdu_sess = num_of_pdu_sess
        self._exceed_load_level_thr_ind = exceed_load_level_thr_ind
        self._confidence = confidence

    @classmethod
    def from_dict(cls, dikt) -> 'SliceLoadLevelInformation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SliceLoadLevelInformation of this SliceLoadLevelInformation.  # noqa: E501
        :rtype: SliceLoadLevelInformation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def load_level_information(self):
        """Gets the load_level_information of this SliceLoadLevelInformation.

        Load level information of the network slice and the optionally associated network slice instance.  # noqa: E501

        :return: The load_level_information of this SliceLoadLevelInformation.
        :rtype: int
        """
        return self._load_level_information

    @load_level_information.setter
    def load_level_information(self, load_level_information):
        """Sets the load_level_information of this SliceLoadLevelInformation.

        Load level information of the network slice and the optionally associated network slice instance.  # noqa: E501

        :param load_level_information: The load_level_information of this SliceLoadLevelInformation.
        :type load_level_information: int
        """
        if load_level_information is None:
            raise ValueError("Invalid value for `load_level_information`, must not be `None`")  # noqa: E501

        self._load_level_information = load_level_information

    @property
    def snssais(self):
        """Gets the snssais of this SliceLoadLevelInformation.

        Identification(s) of network slice to which the subscription applies.  # noqa: E501

        :return: The snssais of this SliceLoadLevelInformation.
        :rtype: List[Snssai]
        """
        return self._snssais

    @snssais.setter
    def snssais(self, snssais):
        """Sets the snssais of this SliceLoadLevelInformation.

        Identification(s) of network slice to which the subscription applies.  # noqa: E501

        :param snssais: The snssais of this SliceLoadLevelInformation.
        :type snssais: List[Snssai]
        """
        if snssais is None:
            raise ValueError("Invalid value for `snssais`, must not be `None`")  # noqa: E501
        if snssais is not None and len(snssais) < 1:
            raise ValueError("Invalid value for `snssais`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._snssais = snssais

    @property
    def num_of_ues(self):
        """Gets the num_of_ues of this SliceLoadLevelInformation.


        :return: The num_of_ues of this SliceLoadLevelInformation.
        :rtype: NumberAverage
        """
        return self._num_of_ues

    @num_of_ues.setter
    def num_of_ues(self, num_of_ues):
        """Sets the num_of_ues of this SliceLoadLevelInformation.


        :param num_of_ues: The num_of_ues of this SliceLoadLevelInformation.
        :type num_of_ues: NumberAverage
        """

        self._num_of_ues = num_of_ues

    @property
    def num_of_pdu_sess(self):
        """Gets the num_of_pdu_sess of this SliceLoadLevelInformation.


        :return: The num_of_pdu_sess of this SliceLoadLevelInformation.
        :rtype: NumberAverage
        """
        return self._num_of_pdu_sess

    @num_of_pdu_sess.setter
    def num_of_pdu_sess(self, num_of_pdu_sess):
        """Sets the num_of_pdu_sess of this SliceLoadLevelInformation.


        :param num_of_pdu_sess: The num_of_pdu_sess of this SliceLoadLevelInformation.
        :type num_of_pdu_sess: NumberAverage
        """

        self._num_of_pdu_sess = num_of_pdu_sess

    @property
    def exceed_load_level_thr_ind(self):
        """Gets the exceed_load_level_thr_ind of this SliceLoadLevelInformation.


        :return: The exceed_load_level_thr_ind of this SliceLoadLevelInformation.
        :rtype: bool
        """
        return self._exceed_load_level_thr_ind

    @exceed_load_level_thr_ind.setter
    def exceed_load_level_thr_ind(self, exceed_load_level_thr_ind):
        """Sets the exceed_load_level_thr_ind of this SliceLoadLevelInformation.


        :param exceed_load_level_thr_ind: The exceed_load_level_thr_ind of this SliceLoadLevelInformation.
        :type exceed_load_level_thr_ind: bool
        """

        self._exceed_load_level_thr_ind = exceed_load_level_thr_ind

    @property
    def confidence(self):
        """Gets the confidence of this SliceLoadLevelInformation.

        Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.  # noqa: E501

        :return: The confidence of this SliceLoadLevelInformation.
        :rtype: int
        """
        return self._confidence

    @confidence.setter
    def confidence(self, confidence):
        """Sets the confidence of this SliceLoadLevelInformation.

        Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.  # noqa: E501

        :param confidence: The confidence of this SliceLoadLevelInformation.
        :type confidence: int
        """
        if confidence is not None and confidence < 0:  # noqa: E501
            raise ValueError("Invalid value for `confidence`, must be a value greater than or equal to `0`")  # noqa: E501

        self._confidence = confidence
