# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ThresholdLevel(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, cong_level=None, nf_load_level=None, nf_cpu_usage=None, nf_memory_usage=None, nf_storage_usage=None):  # noqa: E501
        """ThresholdLevel - a model defined in OpenAPI

        :param cong_level: The cong_level of this ThresholdLevel.  # noqa: E501
        :type cong_level: int
        :param nf_load_level: The nf_load_level of this ThresholdLevel.  # noqa: E501
        :type nf_load_level: int
        :param nf_cpu_usage: The nf_cpu_usage of this ThresholdLevel.  # noqa: E501
        :type nf_cpu_usage: int
        :param nf_memory_usage: The nf_memory_usage of this ThresholdLevel.  # noqa: E501
        :type nf_memory_usage: int
        :param nf_storage_usage: The nf_storage_usage of this ThresholdLevel.  # noqa: E501
        :type nf_storage_usage: int
        """
        self.openapi_types = {
            'cong_level': int,
            'nf_load_level': int,
            'nf_cpu_usage': int,
            'nf_memory_usage': int,
            'nf_storage_usage': int
        }

        self.attribute_map = {
            'cong_level': 'congLevel',
            'nf_load_level': 'nfLoadLevel',
            'nf_cpu_usage': 'nfCpuUsage',
            'nf_memory_usage': 'nfMemoryUsage',
            'nf_storage_usage': 'nfStorageUsage'
        }

        self._cong_level = cong_level
        self._nf_load_level = nf_load_level
        self._nf_cpu_usage = nf_cpu_usage
        self._nf_memory_usage = nf_memory_usage
        self._nf_storage_usage = nf_storage_usage

    @classmethod
    def from_dict(cls, dikt) -> 'ThresholdLevel':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ThresholdLevel of this ThresholdLevel.  # noqa: E501
        :rtype: ThresholdLevel
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cong_level(self):
        """Gets the cong_level of this ThresholdLevel.


        :return: The cong_level of this ThresholdLevel.
        :rtype: int
        """
        return self._cong_level

    @cong_level.setter
    def cong_level(self, cong_level):
        """Sets the cong_level of this ThresholdLevel.


        :param cong_level: The cong_level of this ThresholdLevel.
        :type cong_level: int
        """

        self._cong_level = cong_level

    @property
    def nf_load_level(self):
        """Gets the nf_load_level of this ThresholdLevel.


        :return: The nf_load_level of this ThresholdLevel.
        :rtype: int
        """
        return self._nf_load_level

    @nf_load_level.setter
    def nf_load_level(self, nf_load_level):
        """Sets the nf_load_level of this ThresholdLevel.


        :param nf_load_level: The nf_load_level of this ThresholdLevel.
        :type nf_load_level: int
        """

        self._nf_load_level = nf_load_level

    @property
    def nf_cpu_usage(self):
        """Gets the nf_cpu_usage of this ThresholdLevel.


        :return: The nf_cpu_usage of this ThresholdLevel.
        :rtype: int
        """
        return self._nf_cpu_usage

    @nf_cpu_usage.setter
    def nf_cpu_usage(self, nf_cpu_usage):
        """Sets the nf_cpu_usage of this ThresholdLevel.


        :param nf_cpu_usage: The nf_cpu_usage of this ThresholdLevel.
        :type nf_cpu_usage: int
        """

        self._nf_cpu_usage = nf_cpu_usage

    @property
    def nf_memory_usage(self):
        """Gets the nf_memory_usage of this ThresholdLevel.


        :return: The nf_memory_usage of this ThresholdLevel.
        :rtype: int
        """
        return self._nf_memory_usage

    @nf_memory_usage.setter
    def nf_memory_usage(self, nf_memory_usage):
        """Sets the nf_memory_usage of this ThresholdLevel.


        :param nf_memory_usage: The nf_memory_usage of this ThresholdLevel.
        :type nf_memory_usage: int
        """

        self._nf_memory_usage = nf_memory_usage

    @property
    def nf_storage_usage(self):
        """Gets the nf_storage_usage of this ThresholdLevel.


        :return: The nf_storage_usage of this ThresholdLevel.
        :rtype: int
        """
        return self._nf_storage_usage

    @nf_storage_usage.setter
    def nf_storage_usage(self, nf_storage_usage):
        """Sets the nf_storage_usage of this ThresholdLevel.


        :param nf_storage_usage: The nf_storage_usage of this ThresholdLevel.
        :type nf_storage_usage: int
        """

        self._nf_storage_usage = nf_storage_usage
